### ISSUE TITLE
Adding new source issue

### ISSUE THREAD

**Issue by jmielczarkowski** [tuyen-vuduc/dotnet-mapbox-quickstart#1]
Hi,

I was trying to add my own vector tiles source programatically and it didn't work well. What I did is:

1. Load default style from mapbox studio via url

 ```
            mapboxMap.LoadStyleUri("mapbox://styles/myacc/cllde6avf00yt01qsem1jggzx", styleLoadedListener);
```

2. On styleLoadedListener I've added vector tiles source like:

            var url = "http://192.168.31.163:3000/herbicide/{z}/{x}/{y}";
            var jsonArray = new GoogleGson.JsonArray();
            foreach (var str in new string[] { url })
            {
                jsonArray.Add(new JsonPrimitive(str));
            }

            var sourceProperties = new JsonObject();
            sourceProperties.Add("type", new JsonPrimitive("vector"));
            sourceProperties.Add("tilejson", new JsonPrimitive("herbicide"));
            sourceProperties.Add("sourceId", new JsonPrimitive("herbicide"));
            sourceProperties.Add("tiles", jsonArray);

            // Convert the JsonObject to a Value
            var sourceValue = new Value(sourceProperties.ToString());

            // 2. Add the VectorSource to the style
            p0.AddStyleSource(SOURCE_ID, sourceValue);

When I check collection of objects in StylesSources there were only two objects mapped as Com.Mapbox.Maps.StyleObjectInfo, both comes from Uri loaded default style.

**Comment by tuyen-vuduc** [comment]
@jmielczarkowski Can you make that work with native Java/Kotlin?

**Comment by tuyen-vuduc** [comment]
@jmielczarkowski Can we close this issue?

**Comment by jmielczarkowski** [comment]
Yeah let's close. I manage to handle it using styles.json modification.
