### ISSUE TITLE
Running project on iPhone simulator / showing map box map

### ISSUE THREAD

**Issue by sklyarovaleksey** [tuyen-vuduc/dotnet-mapbox-quickstart#3]
Project launched perfectly on Android simulator and real device, but on iOS Simulator I experience problem.
It look like I have wrong MAPBOX_ACCESS_TOKEN, however this token work perfectly in android.
I would be appreciated if you give me a hand.

![3cdc2584-0ba1-4181-bc3a-547bb4183533](https://github.com/tuyen-vuduc/dotnet-mapbox-quickstart/assets/42214235/219946f3-f9b9-4787-bd48-44ea87cab668)

**Comment by tuyen-vuduc** [comment]
duplicated of #2 . Still looking around...
